services:
  database:
    image: "mysql"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pwd

  api:
    image: viniciosromano/gs2-sem2:latest
    depends_on:
      - database
    ports:
      - 22120:22120
    #    env_file:
    #       - .env
    environment:
      - PROFILE=prd
      - DATABASE_URL=jdbc:mysql://database:3306/api?createDatabaseIfNotExist=true
      - DATABASE_USER=root
      - DATABASE_PWD=root_pwd